### ISSUE TITLE
Audio Urls does not work

### ISSUE THREAD

**Issue by kamrankr** [miguelmota/mixcloud-audio#1]
The response array of urls  throws 404
Test URL : https://www.mixcloud.com/Bonobo
Response from the script
[ 'https://stream4.mixcloud.com/c/m4a/64/4/a/3/e/6711-093c-44a6-88f4-43c9698512ad.m4a',
  ... ]

All urls throw 404!

**Comment by miguelmota** [comment]
@kamrankr looks like mixcloud updated their endpoints and now use mp3u8 playlist stream endpoints. This means it'll no longer returns m4a urls and requires additional work to glue it together.

This module is deprecated as as of now. 

Happy to merge in PRs.

Thanks for reporting!
